channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy
  - matplotlib
  - seaborn
  - tensorflow==1.12.0
  - pytorch==1.0.0
  - pip:
    - tensorflow-probability==0.5.0
    - pyro-ppl==0.3.0
